package com.test.core.strings;


//https://www.youtube.com/watch?v=dCt9sfZV8Sg : #58 Object Class equals toString hashcode in Java

class Laptop{
    String model;
    int price;

   public String toString(){
        return model +" : "+ price;
    }

    public boolean equals(Laptop that){
        if(this.model.equals(that.model) && this.price==that.price)//string comparision and number comparision
            return true;
        else
            return false;
    }
}

public class ToString1 {
    public static void main(String[] args) {
        Laptop l1=new Laptop();
       l1.model="Dell";
        l1.price=50000;

        Laptop l2=new Laptop();
        l2.model="Dell";
        l2.price=50000;

        //System.out.println("Without toString() "+l1); //Laptop@49c2faae
        // by default calls toString() method of Object class which prints hashcode

        System.out.println("Laptop 1 details: "+l1);//calls toString() method internally
        System.out.println("Laptop 2 details: "+l2);

        System.out.println("Are both laptops equal? "+l1.equals(l2));
    }
}

//alternative we can use equals, hashcode and to string generated by IDE, as it adds null checks and type checks
